version: '3.9'
services:
  nginx:
    image: nginx:1.27-bookworm
    container_name: nginx 
    environment:
      - TZ=Europe/Berlin
    # restart: always
    volumes:
    - ./nginx/etc/nginx/:/etc/nginx/:ro
    - ./letsencrypt/www/:/var/www/letsencrypt/:ro
    - ./letsencrypt/conf/:/etc/letsencrypt/:ro
    - ./nginx/log/:/var/log/nginx/:rw
    ports:
    - "80:80"
    - "443:443"
    networks:
      http: {}
  lldap:
    image: lldap/lldap:stable
    container_name: lldap
    #ports:
      ## We do not map ports because we set lldap behind the nginx in a private network
    volumes:
      - "./lldap/data:/data"
    environment:
      - TZ=Europe/Berlin
      - LLDAP_LDAP_BASE_DN=dc=mazze,dc=org
    networks:
      http: {}
  whoami:
    image: traefik/whoami
    container_name: whoami
    networks:
      http: {}
  authelia:
    image: authelia/authelia:4.39
    container_name: authelia
    environment:
      - TZ=Europe/Berlin
    networks:
      http: {}
  # letsencrypt:
  #   image: certbot/certbot:v3.3.0
  #   volumes:
  #     - ./letsencrypt/www/:/var/www/certbot/:rw
  #     - ./letsencrypt/conf/:/etc/letsencrypt/:rw
  #   networks:
  #     http: {}
  # oauth2-proxy:
  #   image: quay.io/oauth2-proxy/oauth2-proxy:v7.9.0
  #   ports: []
  #   hostname: oauth2-proxy
  #   container_name: oauth2-proxy
  #   command: --config /oauth2-proxy.cfg
  #   volumes:
  #     - "./oauth2-proxy-nginx.cfg:/oauth2-proxy.cfg"
  #   networks:
  #     oauth2-proxy: {}
  #     dex: {}
  #     etcd: {}
  #     httpbin: {}
  #   depends_on:
  #     - dex
  #     - httpbin
  # nginx:
  #   depends_on:
  #     - oauth2-proxy
  #   container_name: nginx
  #   image: nginx:1.28
  #   restart: unless-stopped
  #   ports:
  #     - 80:80/tcp
  #   hostname: nginx
  #   volumes:
  #     - "./nginx.conf:/etc/nginx/conf.d/default.conf"
  #   networks:
  #     oauth2-proxy: {}
  #     dex: {}
  #     etcd: {}
  #     httpbin: {}
  # dex:
  #   container_name: dex
  #   image: ghcr.io/dexidp/dex:v2.42.1
  #   command: dex serve /dex.yaml
  #   hostname: dex
  #   volumes:
  #     - "./dex.yaml:/dex.yaml"
  #   restart: unless-stopped
  #   ports:
  #     - 4190:4190/tcp
  #   networks:
  #     dex:
  #       aliases:
  #         - dex.localtest.me
  #     etcd: {}
  #   depends_on:
  #     - etcd
  # httpbin:
  #   container_name: httpbin
  #   image: kennethreitz/httpbin
  #   ports:
  #     - 8080:80/tcp
  #   networks:
  #     httpbin:
  #       aliases:
  #         - httpbin.localtest.me
  # etcd:
  #   container_name: etcd
  #   image: gcr.io/etcd-development/etcd:v3.5.21
  #   entrypoint: /usr/local/bin/etcd
  #   command:
  #     - --listen-client-urls=http://0.0.0.0:2379
  #     - --advertise-client-urls=http://etcd:2379
  #   networks:
  #     etcd: {}
networks:
  http: 
    name: http
    external: true