version: '3.9'
services:
  nginx:
    build:
      context: ./nginx
    # image: nginx:1.27-bookworm
    container_name: nginx 
    environment:
      - TZ=Europe/Berlin
    # restart: always
    volumes:
    - ./nginx/etc/nginx/:/etc/nginx/:ro
    - ./letsencrypt/www/:/var/www/letsencrypt/:ro
    - ./letsencrypt/conf/:/etc/letsencrypt/:ro
    - ./nginx/etc/wireguard/:/etc/wireguard/:ro
    - ./nginx/99-wireguard.sh:/docker-entrypoint.d/99-wireguard.sh:ro
    - ./nginx/log/:/var/log/nginx/:rw
    ports:
    - "80:80"
    - "443:443"
    - "51820:51820/udp"
    networks:
      http: {}
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
  # lldap:
  #   image: lldap/lldap:stable
  #   container_name: lldap
  #   #ports:
  #     ## We do not map ports because we set lldap behind the nginx in a private network
  #   volumes:
  #     - "./lldap/data:/data"
  #   environment:
  #     - TZ=Europe/Berlin
  #     - LLDAP_LDAP_BASE_DN=dc=mazze,dc=org
  #   networks:
  #     http: {}
  # authelia:
  #   image: authelia/authelia:4.39
  #   container_name: authelia
  #   volumes:
  #   - ./authelia/configuration.yml:/config/configuration.yml:ro
  #   environment:
  #     - TZ=Europe/Berlin
  #   networks:
  #     http: {}
  whoami:
    image: traefik/whoami
    container_name: whoami
    networks:
      http: {}
  # letsencrypt:
  #   image: certbot/certbot:v3.3.0
  #   volumes:
  #     - ./letsencrypt/www/:/var/www/certbot/:rw
  #     - ./letsencrypt/conf/:/etc/letsencrypt/:rw
  #   networks:
  #     http: {}
networks:
  http: 
    name: http
    external: true